### ISSUE TITLE
Crashes on Start due to NameError

### ISSUE THREAD

**Issue by kentarospin98** [enkiv2/fern#6]
https://github.com/enkiv2/fern/blob/0244f1a5f09843d8f98dcbaf777224977fac560e/fern#L755

Raises

```
Traceback (most recent call last):
  File "/home/kensp/Documents/fern/./fern", line 905, in <module>
    main()
  File "/home/kensp/Documents/fern/./fern", line 894, in main
    else: tl=getTimeline("all", verbose=True)
  File "/home/kensp/Documents/fern/./fern", line 644, in getTimeline
    for item in which.split(): tl.extend(getTimeline(item, **kw_args))
  File "/home/kensp/Documents/fern/./fern", line 666, in getTimeline
    tl=ensureCached(tl)
  File "/home/kensp/Documents/fern/./fern", line 755, in ensureCached
    elif type(toot) in [str, unicode]: # TID
NameError: name 'unicode' is not defined
```

**Comment by kentarospin98** [comment]
Looks like these issues are python 3 specific. Like how python3 strings are unicode by default so there's no `unicode` type.
